package modelo;
// Generated 16-oct-2024 11:43:21 by Hibernate Tools 4.3.1

import java.math.BigDecimal;

/**
 * Equipos generated by hbm2java
 */
public class Equipos implements java.io.Serializable {

    private int idEquipo;
    private String marca;
    private String modelo;
    private String descripcion;
    private Integer pulgadasPantalla;
    private Integer capacidadDisco;
    private Integer gbMemoria;
    private BigDecimal precio;

    public Equipos() {
    }

    public Equipos(int idEquipo) {
        this.idEquipo = idEquipo;
    }

    public Equipos(int idEquipo, String marca, String modelo, String descripcion, Integer pulgadasPantalla, Integer capacidadDisco, Integer gbMemoria, BigDecimal precio) {
        this.idEquipo = idEquipo;
        this.marca = marca;
        this.modelo = modelo;
        this.descripcion = descripcion;
        this.pulgadasPantalla = pulgadasPantalla;
        this.capacidadDisco = capacidadDisco;
        this.gbMemoria = gbMemoria;
        this.precio = precio;
    }

    public int getIdEquipo() {
        return this.idEquipo;
    }

    public void setIdEquipo(int idEquipo) {
        this.idEquipo = idEquipo;
    }

    public String getMarca() {
        return this.marca;
    }

    public void setMarca(String marca) {
        this.marca = marca;
    }

    public String getModelo() {
        return this.modelo;
    }

    public void setModelo(String modelo) {
        this.modelo = modelo;
    }

    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public Integer getPulgadasPantalla() {
        return this.pulgadasPantalla;
    }

    public void setPulgadasPantalla(Integer pulgadasPantalla) {
        this.pulgadasPantalla = pulgadasPantalla;
    }

    public Integer getCapacidadDisco() {
        return this.capacidadDisco;
    }

    public void setCapacidadDisco(Integer capacidadDisco) {
        this.capacidadDisco = capacidadDisco;
    }

    public Integer getGbMemoria() {
        return this.gbMemoria;
    }

    public void setGbMemoria(Integer gbMemoria) {
        this.gbMemoria = gbMemoria;
    }

    public BigDecimal getPrecio() {
        return this.precio;
    }

    public void setPrecio(BigDecimal precio) {
        this.precio = precio;
    }

    @Override
    public String toString() {
        return "Equipos{" + "idEquipo=" + idEquipo + ", marca=" + marca + ", modelo=" + modelo + ", descripcion=" + descripcion + ", pulgadasPantalla=" + pulgadasPantalla + ", capacidadDisco=" + capacidadDisco + ", gbMemoria=" + gbMemoria + ", precio=" + precio + '}';
    }
}
