package Modelos;
// Generated 15-oct-2024 13:41:39 by Hibernate Tools 4.3.1



/**
 * Socios generated by hbm2java
 */
public class Socios  implements java.io.Serializable {


     private int codsocio;
     private String nombre;
     private String apellidos;
     private String direccion;
     private String telefono;
     private String poblacion;

    public Socios() {
    }

	
    public Socios(int codsocio) {
        this.codsocio = codsocio;
    }
    public Socios(int codsocio, String nombre, String apellidos, String direccion, String telefono, String poblacion) {
       this.codsocio = codsocio;
       this.nombre = nombre;
       this.apellidos = apellidos;
       this.direccion = direccion;
       this.telefono = telefono;
       this.poblacion = poblacion;
    }
   
    public int getCodsocio() {
        return this.codsocio;
    }
    
    public void setCodsocio(int codsocio) {
        this.codsocio = codsocio;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getPoblacion() {
        return this.poblacion;
    }
    
    public void setPoblacion(String poblacion) {
        this.poblacion = poblacion;
    }

    @Override
    public String toString() {
        return "Socios{" + "codsocio=" + codsocio + ", nombre=" + nombre + ", apellidos=" + apellidos + ", direccion=" + direccion + ", telefono=" + telefono + ", poblacion=" + poblacion + '}';
    }




}


